export default [
  {
    id: 1,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 2,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 3,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 4,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 5,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 6,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 7,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 8,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 9,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
  {
    id: 10,
    image: "/Doctors/doctor-thumb-01.jpg",
    title: "Dr. Darren Elder",
    description: "MDS - Periodontology and Oral Implantology, BDS",
    specilist: "Denist",
    rating: 4,
    state: "Florida, USA",
    location: "Darbhanga, Bihar",
    landMark: "Near India Gate",
    experience: "12 Years",
  },
];
